"""extract_animal_events

Revision ID: 10ce94b1b1c0
Revises: 6e88a0cde6f9
Create Date: 2026-02-05 20:22:59.030866

"""

import csv
import os
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10ce94b1b1c0"
down_revision: Union[str, None] = "6e88a0cde6f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "animal_event_type",
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )

    # Populate animal_event_type
    csv_path = os.path.join(
        os.path.dirname(__file__), "../../initial_data/animal_events.csv"
    )
    data = []
    if os.path.exists(csv_path):
        with open(csv_path, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                data.append(row)

    if data:
        animal_event_type = sa.table(
            "animal_event_type",
            sa.column("code", sa.String),
            sa.column("description", sa.String),
            sa.column("category", sa.String),
        )
        op.bulk_insert(animal_event_type, data)

    op.create_foreign_key(
        "fk_animal_log_event_type",
        "animal_log",
        "animal_event_type",
        ["event"],
        ["code"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_animal_log_event_type", "animal_log", type_="foreignkey"
    )
    op.drop_table("animal_event_type")
    # ### end Alembic commands ###
