"""add doc kind uploadable rendered flags

Revision ID: 12a20b0bf3d3
Revises: 38979c9ad66f
Create Date: 2024-07-27 16:09:37.260640

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12a20b0bf3d3"
down_revision: Union[str, None] = "38979c9ad66f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_kind",
        sa.Column("uploadable", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.add_column(
        "document_kind",
        sa.Column("rendered", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_kind", "rendered")
    op.drop_column("document_kind", "uploadable")
    # ### end Alembic commands ###
