"""races

Revision ID: 1bb12e9dcab1
Revises: 3bebd7731267
Create Date: 2023-11-24 23:23:14.368436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from hermadata.database.alembic.import_initial_data import import_races


# revision identifiers, used by Alembic.
revision: str = "1bb12e9dcab1"
down_revision: Union[str, None] = "3bebd7731267"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "race",
        sa.Column("id", sa.String(length=1), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )

    import_races(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("race")

    # ### end Alembic commands ###
