"""document kind code 3 characters

Revision ID: 368a2d2d72fd
Revises: bd1383d9f555
Create Date: 2024-12-29 11:47:20.818429

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from hermadata.database.models import DocumentKind

# revision identifiers, used by Alembic.
revision: str = "368a2d2d72fd"
down_revision: Union[str, None] = "bd1383d9f555"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_kind",
        "code",
        existing_type=mysql.VARCHAR(length=2),
        type_=sa.String(length=3),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.get_bind().execute(sa.delete(DocumentKind))
    op.alter_column(
        "document_kind",
        "code",
        existing_type=sa.String(length=3),
        type_=mysql.VARCHAR(length=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
