"""comuni and province

Revision ID: 3bebd7731267
Revises:
Create Date: 2023-11-24 23:20:22.007586

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from hermadata.database.alembic.import_initial_data import (
    import_comuni_and_province,
)

# revision identifiers, used by Alembic.
revision: str = "3bebd7731267"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "provincia",
        sa.Column("id", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "comune",
        sa.Column("id", sa.String(length=4), nullable=False),
        sa.Column("provincia", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["provincia"],
            ["provincia.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    import_comuni_and_province(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("comune")
    op.drop_table("provincia")
    # ### end Alembic commands ###
