"""add without_chip to animal_entry

Revision ID: 45abcad6b93d
Revises: 10ce94b1b1c0
Create Date: 2026-02-09 21:59:46.020400

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45abcad6b93d"
down_revision: Union[str, None] = "10ce94b1b1c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "animal_entry",
        sa.Column(
            "without_chip",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("animal_entry", "without_chip")
    # ### end Alembic commands ###
