"""Add city_codes to users

Revision ID: 4794e65a82b4
Revises: d213345b7e5e
Create Date: 2026-01-27 19:31:06.816823

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4794e65a82b4"
down_revision: Union[str, None] = "d213345b7e5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("city_codes", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "city_codes")
    # ### end Alembic commands ###
