"""add user_id to animal_log table

Revision ID: 6e88a0cde6f9
Revises: 4794e65a82b4
Create Date: 2026-02-02 19:42:34.503164

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e88a0cde6f9"
down_revision: Union[str, None] = "4794e65a82b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "animal_log", sa.Column("user_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "fk_animal_log_user", "animal_log", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_animal_log_user", "animal_log", type_="foreignkey")
    op.drop_column("animal_log", "user_id")
    # ### end Alembic commands ###
