"""add adoption custody place

Revision ID: 76eed782393e
Revises: 73044398fda6
Create Date: 2025-02-25 22:11:03.736107

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76eed782393e"
down_revision: Union[str, None] = "73044398fda6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("adoption", sa.Column("location_address", sa.String(length=100), nullable=True))
    op.add_column("adoption", sa.Column("location_city_code", sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("adoption", "location_city_code")
    op.drop_column("adoption", "location_address")
    # ### end Alembic commands ###
