"""rename medical service table

Revision ID: aad6f2ff9514
Revises: cd945a9f6044
Create Date: 2024-11-21 16:15:59.214051

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "aad6f2ff9514"
down_revision: Union[str, None] = "cd945a9f6044"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vet_service_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("causal", sa.String(length=100), nullable=False),
        sa.Column("price", sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column("vet_id", sa.Integer(), nullable=False),
        sa.Column("animal_id", sa.Integer(), nullable=False),
        sa.Column("performed_at", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["animal_id"],
            ["animal.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vet_id"],
            ["vet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("medical_record")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "medical_record",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("causal", mysql.VARCHAR(length=100), nullable=False),
        sa.Column(
            "price", mysql.DECIMAL(precision=15, scale=2), nullable=False
        ),
        sa.Column(
            "vet_id", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "animal_id", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("performed_at", sa.DATE(), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["animal_id"], ["animal.id"], name="medical_record_ibfk_1"
        ),
        sa.ForeignKeyConstraint(
            ["vet_id"], ["vet.id"], name="medical_record_ibfk_2"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("vet_service_record")

    # ### end Alembic commands ###
