"""change vet column names

Revision ID: cd945a9f6044
Revises: cda8d9fa4839
Create Date: 2024-11-16 10:59:08.496166

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "cd945a9f6044"
down_revision: Union[str, None] = "cda8d9fa4839"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vet", sa.Column("name", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "vet", sa.Column("surname", sa.String(length=100), nullable=True)
    )
    op.drop_column("vet", "cognome")
    op.drop_column("vet", "nome")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vet", sa.Column("nome", mysql.VARCHAR(length=100), nullable=True)
    )
    op.add_column(
        "vet", sa.Column("cognome", mysql.VARCHAR(length=100), nullable=True)
    )
    op.drop_column("vet", "surname")
    op.drop_column("vet", "name")
    # ### end Alembic commands ###
