"""add animal doc title

Revision ID: cda8d9fa4839
Revises: 12a20b0bf3d3
Create Date: 2024-07-27 17:15:46.286108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cda8d9fa4839'
down_revision: Union[str, None] = '12a20b0bf3d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_document', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal_document', 'title')
    # ### end Alembic commands ###
