"""add in_shelter_from column to animal table

Revision ID: d213345b7e5e
Revises: 6ebfc1ffc63b
Create Date: 2025-11-15 15:52:33.711840

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d213345b7e5e"
down_revision: Union[str, None] = "6ebfc1ffc63b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "animal",
        sa.Column("in_shelter_from", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("animal", "in_shelter_from")
    # ### end Alembic commands ###
